### ISSUE TITLE
Question: can I use openwsman for asset tracking?

### ISSUE THREAD

**Issue by floe** [Openwsman/openwsman#101]
Apologies if this is a "Stupid Question (TM)", but I've been looking for quite some time for an open-source tools that lets me do asset tracking, i.e. run it on a known server and have mobile devices, such as laptops, "phone home" with their current, dynamically assigned client IP to this server. Can I use openwsman (or some other tool from the suite) for this purpose?

**Comment by kkaempf** [comment]
Openwsman is the transport layer, your asset management tool might need to talk to

- Intel AMT
- Dell iDRAC
- HP iLO
- VMware
- Windows remote management

All these interfaces reveal information you might want to track as assets.
