### ISSUE TITLE
`ssl_cipher_list=` does not do what `openssl ciphers` would do

### ISSUE THREAD

**Issue by AloisMahdal** [Openwsman/openwsman#111]
I'm not sure if there are real-life use cases[1], so take this with a grain of salt.

Using empty string with `openssl ciphers` selects no ciphers.  That is, by observing this command, user could come to conclusion that passing empty string is a possible way to disable everything.

But, openwsmand does not behave the same way:

    ssl_cipher_list=

results in enabling all (default) ciphers.  My (= C n00b level) reading of shttpd.c seems to confirm that empty value means the cipher list is just left alone.

What do you think?

---

[1]: Most plausible I can think of is if someone generates the config based on pre-approved cipher list and for some reason their list ends up being empty.

**Comment by AloisMahdal** [comment]
(Note that this was originally posted to openwsman-devel as a question.  Few days ago, just before the last spam storm which resulted in deletion of the mailing list.)

**Comment by kkaempf** [comment]
Well, `ssl_cipher_list=` just calls [`SSL_CTX_set_cipher_list`](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_cipher_list.html) which doesn't clearly describe the semantics of passing an empty string.

But I'll add a warning to the log if `ssl_cipher_list` is empty.
