### ISSUE TITLE
Add CI builds to improve pull request and code quality

### ISSUE THREAD

**Issue by jeking3** [Openwsman/openwsman#112]
CI builds would run every pull request allowing code submitters to self-service and provide code that passes tests before going through a code review.  It can also periodically run master and develop through builds to prove out code correctness (i.e. does it compile, link, and pass unit tests?) as well as provide code coverage and static code analysis.

You could add matrix jobs that build every combination of:

* autoconf or cmake
* openssl 1.0.x or 1.1.x
* linux or osx

as well as jobs that do:

* code coverage (integrate with codecov.io)
* ubsan
* coverity scan, if it ever comes back up...

etc...

**Comment by kkaempf** [comment]
Respective pull requests are happily accepted.

**Comment by jeking3** [comment]
Closing the issue reduces the chance someone will remember to do it.
