### ISSUE TITLE
Using __ in the field name brokes VS 2017 compilation

### ISSUE THREAD

**Issue by rabliyev** [Openwsman/openwsman#114]
File: include/wsman-client-api.h

**client_opt_t** struct using two prefix underscore in the field  name: char ***__reserved**[16];
which is not supported by Visual Studio 2017 compiler

changing it to char * **reserved__**[16]; solves the issue

**Comment by kkaempf** [comment]
Ugh, the ANSI C standard seems to have room for interpretation.
