### ISSUE TITLE
100-continue and servers that does not support that

### ISSUE THREAD

**Issue by ausyskin** [Openwsman/openwsman#131]
Curl if used by openwsman library always sends 100-continue [1].
We have bunch of embedded servers that does not support that header, so
curl continues after 1sec timeout. That creates big delays for long conversations.

Now in our code I hard-disable the header:
```
diff -ru openwsman/src/lib/wsman-curl-client-transport.c ./src/lib/wsman-curl-client-transport.c
--- openwsman/src/lib/wsman-curl-client-transport.c        2019-09-24 10:59:52.634048988 +0300
+++ ./src/lib/wsman-curl-client-transport.c     2019-09-18 17:08:50.494829963 +0300
@@ -521,9 +521,6 @@
        }
 #endif

-       /* Don't request 100-continue*/
-       headers = curl_slist_append(headers, "Expect:");
-
        r = curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
        if (r != CURLE_OK) {
                cl->fault_string = u_strdup(curl_easy_strerror(r));
```

Is it the right way to do?
Can we make it default openwsman behavior?
Or add some parameter to have it as option without patching code?

[1] https://gms.tf/when-curl-sends-100-continue.html

**Comment by kkaempf** [comment]
> Curl if used by openwsman library always sends 100-continue [1].
> We have bunch of embedded servers that does not support that header

Complain to the embedded system's vendor :wink:


> 
> Is it the right way to do?

No, since it changes openwsman semantics for everyone.

> Can we make it default openwsman behavior?

No, with the same reason.

> Or add some parameter to have it as option without patching code?

Option yes, but this of course needs code patches in openwsman :-/

**Comment by ausyskin** [comment]
> 
> 
> > Curl if used by openwsman library always sends 100-continue [1].
> > We have bunch of embedded servers that does not support that header
> 
> Complain to the embedded system's vendor 😉
Already :)
> 
> > Is it the right way to do?
> 
> No, since it changes openwsman semantics for everyone.
> 
> > Can we make it default openwsman behavior?
> 
> No, with the same reason.
> 
> > Or add some parameter to have it as option without patching code?
> 
> Option yes, but this of course needs code patches in openwsman :-/
I'm willing to create a relevant patch but I need some guidance where to add such parameter.

**Comment by kkaempf** [comment]
This should give you some guidance: https://github.com/Openwsman/openwsman/commit/13b9432758ac772c5aac60d19cd9c7021fa1ea4c

you need (assuming you do a true/false setting)
- add the (commented out) option to `etc/openwsman.conf`
- a variable to store the option value `static int ...` in `wsmand-daemon.c`
- set the variable by calling `iniparser_getboolean`
- a getter function like `wsmand_options_get_ssl_cipher_list` in the example
- a getter function declaration in `wsmand_daemon.h`

**Comment by ausyskin** [comment]
I need an option for a wsman client, not for a server.
And also we use openwsman as embedded library so it's better not to read configuration from external file.
Now I see two approaches:
1. Use one bit from client_opt_t, fill it with wsmc_set_action_option and copy that bit to flags in _WsManClient
2. Extend iniparser to receive configuration in string and pass parameter through it to flags in _WsManClient.

Which one do you prefer?
I have some WIP branch for (2), it will be bulky solution.

**Comment by ausyskin** [comment]
The branch https://github.com/ausyskin/openwsman/tree/topic_disable_100.
Compile-tested only :)
Both solutions there. Made only to look how much it will cost.
