### ISSUE TITLE
How can we build Openwsman with OpenSSL instead of using WinHTTP APIs

### ISSUE THREAD

**Issue by ganeshkamath89** [Openwsman/openwsman#141]
I noticed that in "wsman-curl-client-transport.c" file you use OpenSSL, but in "wsman-win-client-transport.c" you have use WinHTTP APIs.

OpenSSL is both cross compilable and provides better support. Can you give few pointers on how to build OpenWsMan with OpenSSL?

**Comment by kkaempf** [comment]
I'm sorry, I don't have a Windows development environment. However, I'd happily accept a pull request to support what you ask for ;-)

**Comment by ganeshkamath89** [comment]
@kkaempf , I want to enable TLS 1.3 on Windows version earlier than Windows 10 such as Windows 7. For this, I want to port OpenWSMan from WinHTTP to OpenSSL. I still haven't found out how to go about this process, because the two codes look so different. Do you have any idea if this is done in any open source projects that use OpenWSMan already?

**Comment by ganeshkamath89** [comment]
@kkaempf , I am able to build Curl and Openssl on Windows, so we are enabling TLS 1.3 in our tool by changing the Windows project to use Curl and Openssl.

So you can close this issue

**Comment by kkaempf** [comment]
Closing as of last comment.
