### ISSUE TITLE
/lib64/libwsman_client.so.4: undefined symbol: key_value_create

### ISSUE THREAD

**Issue by StumpfMichael** [Openwsman/openwsman#142]
After installation of rpm with yum of openwsman and wsmancli on CentOS7 wsman doesn't work.

libwsman1.x86_64 2.6.3-6.git4391e5c.el7_6
wsmancli.x86_64   2.6.0-2.el7
sblim-sfcc.x86_64  2.2.5-6.el7

$wsman
/lib64/libwsman_client.so.4: undefined symbol: key_value_create

This c-function is declared in openwsman/include/wsman-key-value.c and realized in openwsman/src/lib/wsman-key-value.c.

Manual installation (cloning from github, make etc.) of libwsman1 and wsmancli doesn't help.

**Comment by kkaempf** [comment]
Please report this to CentOS. I can't help with packaging issues.
