### ISSUE TITLE
Python bindings give "AttributeError: auth_request_callback" when server returns 401

### ISSUE THREAD

**Issue by StumpfMichael** [Openwsman/openwsman#146]
This issue is a repitition of # 35.
 
wsman-client.i:

  /*
   * The Transport instance associated to the client
   */
  WsManTransport *transport() {
    wsmc_transport_init($self, NULL);
    wsmc_transport_set_auth_request_func( $self, auth_request_callback );

    return (WsManTransport *)$self;
  }

  /*
   * Send a (raw) SOAP request to the client
   *
   * call-seq:
   *   client.send_request(XmlDoc.new("<xml ...>...</xml>")) -> Integer
   *
   */
  int send_request(WsXmlDocH request) {
    return wsman_send_request($self, request);
  }

pywsman.py:

    def transport(self):
        """transport(Client self) -> Transport"""
        return _pywsman.Client_transport(self)

    def auth_request_callback(self, *args):
        """auth_request_callback(Transport self, Client client, name auth_type)"""
        return _pywsman.Transport_auth_request_callback(self, *args)

    def send_request(self, *args):
        """send_request(Client self, XmlDoc request) -> int"""
        return _pywsman.Client_send_request(self, *args)

To solve the issue, pywsman.py has to be patched at line 1800 to 1802 as shown above.
Seems to be a problem of SWIG.

**Comment by kkaempf** [comment]
Which version of SWIG are you using ?

**Comment by kkaempf** [comment]
btw, #35 asked for community input from someone with more Python experience than myself.

**Comment by StumpfMichael** [comment]
On CentOS Linux release 7.8.2003 swig answers:

swig -version

SWIG Version 2.0.10

Compiled with g++ [x86_64-redhat-linux-gnu]

I am not sure whether it is a problem of this version. The problem was
already reported a long time ago, possibly with an older swig version.

Am Mo., 21. Sept. 2020 um 11:54 Uhr schrieb Klaus Kämpf <
notifications@github.com>:

**Comment by kkaempf** [comment]
SWIG **2** ??! :open_mouth: [upstream](http://swig.org/) is at **4** !

**Comment by StumpfMichael** [comment]
Yes, the newest rpm version installed by yum on CentOS7 is 2.
Ubuntu 18 newest installed package ist version 3.0.

Tomorrow I will install swig 4 by source and test again on CentOS.

Am Di., 22. Sept. 2020 um 18:11 Uhr schrieb Klaus Kämpf <
notifications@github.com>:

**Comment by StumpfMichael** [comment]
Quick Check with swig 3.0 on ubuntu 18, same issue.

Am Di., 22. Sept. 2020 um 20:50 Uhr schrieb Michael Stumpf <
mi12st34@gmail.com>:

**Comment by StumpfMichael** [comment]
Attached you can find the file pywsman.py created by the latest version of
swig 4.0.2 (see header).
It includes a manually patch in line 2262 - 2265. I am not a swig expert,
perhaps the patch is not very correct, but it resolves the issue which
otherwise still exists.


Am Di., 22. Sept. 2020 um 21:20 Uhr schrieb Michael Stumpf <
mi12st34@gmail.com>:
