### ISSUE TITLE
Help Wanted - Python convert SWIG/XML node to int/str

### ISSUE THREAD

**Issue by ghost** [Openwsman/openwsman#154]
I have a working python script/module (my very first!) that uses openwsman to manage the power state of a computer, but have had a lot of difficulty figuring out how to capture the output of Client.methods().  In the code block below, you can see how I am redirecting stdout to capture print()'s stdout, stripping out the newline generated by the print function, and passing the results from get_version_info().

Coming from a strong powershell background, the way I am doing this feels very wrong to me, and was hoping someone here could show me a better way. I use similar methods to capture the current and available power states, as well as the ReturnValue when sending a RequestPowerStateChange command, which are all integers.

``` python
import sys, io
from time import sleep
import pywsman as pywsman
def get_version_info(client):
    try:
        # --- invoke Identify method
        options = pywsman.ClientOptions()

        for _ in range(10):
            result = client.identify( options )
            if result:
                break
            # Wait 1 second between retries.  AMT controllers are generally
            # very light and may not be comfortable with more frequent
            # queries.
            sleep(1)

        if result is None:
            response_code = client.response_code()
            last_error = client.last_error()
            raise Exception('Host did not respond to query: "{0}"'.format(client.host()), 'Http response code: "{0}"'.format(int(response_code)), 'Last Error: "{0}"'.format(int(last_error)))

        root = result.root()
        prot_version_xml = root.find( pywsman.XML_NS_WSMAN_ID, "ProtocolVersion" )
        prod_vendor_xml = root.find( pywsman.XML_NS_WSMAN_ID, "ProductVendor" )
        prod_version_xml = root.find( pywsman.XML_NS_WSMAN_ID, "ProductVersion" )

        # redirect stdout to capture print strings of desired data
        old_stdout = sys.stdout
        prot_version_stdout = io.StringIO()
        prod_vendor_stdout = io.StringIO()
        prod_version_stdout = io.StringIO()
        sys.stdout = prot_version_stdout
        print(prot_version_xml)
        prot_version = prot_version_stdout.getvalue().strip('\n')
        sys.stdout = prod_vendor_stdout
        print(prod_vendor_xml)
        prod_vendor = prod_vendor_stdout.getvalue().strip('\n')
        sys.stdout = prod_version_stdout
        print(prod_version_xml)
        prod_version = prod_version_stdout.getvalue().strip('\n')
        sys.stdout = old_stdout

        major_version = int(prod_version.split()[1].split('.')[0])

        if major_version >= 9:
            supports_graceful = True
        else:
            supports_graceful = False

        identity = {
            'Protocol': prot_version,
            'Vendor': prod_vendor,
            'Version': prod_version,
            'Graceful': supports_graceful
        }
        return identity
    except Exception as e:
        print(e)

```

**Comment by kkaempf** [comment]
You're looking for the `.text()` method. Applied to any XmlNode (like returned from `.find()`), it returns the 'inner text' of the node.

I'm sorry that there's no good Python documentation for OpenWsman, as I only found `rdoc` for Ruby to work with Swig input files.
Maybe [the Ruby documentation pages](http://openwsman.github.io/rdoc/) can be of help.

**Comment by GP1cdenney** [comment]
``` python
#!/usr/bin/python
import pywsman as pywsman

POWER_STATES = {
    'on': 2,
    'sleep': 4,
    'reboot': 5,
    'hibernate': 7,
    'off': 8,
    'reset': 10,
    'nmi': 11,
    'gracefuloff': 12,
    'gracefulreset': 14
}


hostname = 'host.contoso.com'
username = 'admin'
password = 'PASSWORD'
state = 'on'
powerstate = str(POWER_STATES[state])
timeout = 300
path = '/wsman'
scheme = 'http'
if scheme is 'http':
    port = 16992
else:
    port = 16993


client = pywsman.Client(hostname, port, path, scheme, username, password)


epr_computersystem = pywsman.EndPointReference("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem")
epr_computersystem.add_selector("Name", "ManagedSystem")
epr_computersystem.selector("PowerState")

get_options = pywsman.ClientOptions()
get_options.add_property("UserOfService", epr_computersystem)
get_options.cim_namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_AssociatedPowerManagementService"

for _ in range(10):
    result = client.get(get_options, get_options.cim_namespace)
    if result:
        break
    # Wait 1 second between retries.  AMT controllers are generally
    # very light and may not be comfortable with more frequent
    # queries.
    sleep(1)


# current_state is an xmldoc, but print() returns the desired results
## struggling to determine how to compare the results for validation
current_state = result.body().get("CIM_AssociatedPowerManagementService").get("PowerState")
print(current_state)
current_state.text()
```

Outputs:
> 2
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib64/python3.6/site-packages/pywsman.py", line 221, in <lambda>
>     __getattr__ = lambda self, name: _swig_getattr(self, XmlNode, name)
>   File "/usr/local/lib64/python3.6/site-packages/pywsman.py", line 80, in _swig_getattr
>     raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
> AttributeError: 'XmlNode' object has no attribute 'text'

My understanding is these are not really "Xml" objects but "Swig" objects of Xml objects. For example, there is a current_state.this which is `<Swig Object of type '__WsXmlNode *' at 0xaddress>`

Tabbing the current_state.* gives me the following methods/properties, but none of them return the inner_text that I am looking for, not even .string() which returns the entire xmldoc to string instead of just the node I'm working with:

> current_state.add()
> current_state.add_before()
> current_state.attr()
> current_state.attr_add()
> current_state.attr_count()
> current_state.attr_find()
> current_state.child()
> current_state.doc()
> current_state.dump_file()
> current_state.epr()
> current_state.equal()
> current_state.find()
> current_state.get()
> current_state.name()
> current_state.next()
> current_state.ns()
> current_state.parent()
> current_state.prefix()
> current_state.set_lang()
> current_state.set_ns()
> current_state.set_name()
> current_state.set_text()
> current_state.size()
> current_state.string()
> current_state.this

**Comment by kkaempf** [comment]
Uhm, why is Python not finding the `.text` callback ? 🤔 

I'm a Python illiterate, please bear with me in finding a solution for this problem.

**Comment by GP1cdenney** [comment]
LOL, glad I'm not crazy. This is my very first python project, so I'm also quite illiterate here. I'll try running a few tests to see if maybe .text shows up somewhere else.

**Comment by GP1cdenney** [comment]
Ok, I feel a little dumb. I want to say I had an error trying this before where python couldn't convert __WsXmlNode to string, but apparently all I have to do is `str(current_state)` . I was probably trying to use `int(current_state)` because I wanted to use integer type, and that _does return an error_, but the str() convert method works just fine.

``` python
#!/usr/bin/python
import pywsman as pywsman

POWER_STATES = {
    'on': 2,
    'sleep': 4,
    'reboot': 5,
    'hibernate': 7,
    'off': 8,
    'reset': 10,
    'nmi': 11,
    'gracefuloff': 12,
    'gracefulreset': 14
}


hostname = 'host.contoso.com'
username = 'admin'
password = 'PASSWORD'
state = 'on'
powerstate = str(POWER_STATES[state])
timeout = 300
path = '/wsman'
scheme = 'http'
if scheme is 'http':
    port = 16992
else:
    port = 16993


client = pywsman.Client(hostname, port, path, scheme, username, password)


epr_computersystem = pywsman.EndPointReference("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem")
epr_computersystem.add_selector("Name", "ManagedSystem")
epr_computersystem.selector("PowerState")

get_options = pywsman.ClientOptions()
get_options.add_property("UserOfService", epr_computersystem)
get_options.cim_namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_AssociatedPowerManagementService"

for _ in range(10):
    result = client.get(get_options, get_options.cim_namespace)
    if result:
        break
    # Wait 1 second between retries.  AMT controllers are generally
    # very light and may not be comfortable with more frequent
    # queries.
    sleep(1)


# current_state is an xmldoc, but print() returns the desired results
## struggling to determine how to compare the results for validation
current_state = int(str(result.body().get("CIM_AssociatedPowerManagementService").get("PowerState")))

return current_state

```
> 2

**Comment by GP1cdenney** [comment]
There's definitely no .text callback that I can find, but this workaround suits me just fine and cuts several lines of code out whenever I want to process results of a command.

**Comment by kkaempf** [comment]
Closing as this is a SWIG problem - the [`rename`](https://github.com/Openwsman/openwsman/blob/cc022290720f9e9f5aa4e821a009556f42b86d1e/bindings/wsman-xml.i#L309) isn't properly handled.

Workaround: use `__str__()`
