### ISSUE TITLE
Need support for Transfer-Encoding header in HTTP requests for openwsman.

### ISSUE THREAD

**Issue by avi247** [Openwsman/openwsman#161]
Today, openwsman always looks for content-length to parse the message body. We should add support for Transfer-encoding as well.

And in case a request contains both, content-length and Transfer-encoding. headers, openwsman can ignore the content-length. This will help in avoiding smuggling attacks.

**Comment by kkaempf** [comment]
Web traffic is handled by the `shttpd` library (now renamed to [mongoose](https://code.google.com/archive/p/mongoose)) within openwsman. This library is quite old (~ 15 years!) meanwhile. Newer versions possibly have the support functions you're looking for.
I once looked at porting openwsman over to `mongoose` but the changes are pretty substantial.

I happily accept PRs :wink:

**Comment by avi247** [comment]
Thanks for the response.

I looked here as well https://github.com/Openwsman/openwsman/blob/master/src/server/shttpd/shttpd.c, transenc is not used anywhere. 

Actually we ran Nessus and it is reporting HTTP smuggling Detection (140735) for openwsman and we need to fix this.

In our setup, openwsman is running behind an rhttpproxy server that ignores content-length when an HTTP request comes with both content-length and transfer-encoding. We need to have the same handling in openwsman as well to avoid any HTTP smuggling attacks. Since openwsman doesn't support Transfer-encoding, can I just check if the incoming request has both these headers and if that's is the case then just return 400, "Bad request"? I am new to openwsan so need your help to confirm my understanding, thanks for your help!

**Comment by kkaempf** [comment]
I don't have experience with http headers, I can't say how to handle this situation in a compatible manner.

I'm sorry, but I have to close this as "won't fix".

Maybe you can hire an open source developer to help fix this in openwsman ? 😉
