### ISSUE TITLE
Packaging for Debian

### ISSUE THREAD

**Issue by jkugler** [Openwsman/openwsman#189]
Hello! I e-mailed the contact e-mail on https://openwsman.github.io/ this December but never heard back.

We (metify.io) would like to contribute to the project by maintaining  a package for Debian.

There are currently Ubuntu packages, but they have gone stale.

We'd like to contribute to Debian, and possibly move the package into Ubuntu at some point.

Who is a good contact for us as we take this on?

Thanks!

**Comment by kkaempf** [comment]
Thanks for helping out !

The best start is the [openSUSE build service](https://build.opensuse.org/) which already has the [openwsman package](https://build.opensuse.org/package/show/systemsmanagement:wbem/openwsman)

Start with branching (forking) the existing package, enable your preferred Debian/Ubuntu distributions, and then submit back.

**Comment by kkaempf** [comment]
Answered, closing.
