### ISSUE TITLE
Build fails without Ruby

### ISSUE THREAD

**Issue by Malvineous** [Openwsman/openwsman#194]
I don't have Ruby installed so I don't need the bindings, so I went ahead and built it:
```
-- Ruby: RUBY_EXECUTABLE-NOTFOUND
-- Ruby Library: RUBY_LIBRARY-NOTFOUND
-- Ruby Include: RUBY_INCLUDE_PATH-NOTFOUND
-- Building Ruby bindings
-- ************  WARNING  *************
-- Didn't Find Ruby Headers... Not Building Ruby Bindings
-- ************************************
```
Ok fine, no problem.  The build completes successfully, but when I run `make install` it breaks half way through with:
```
make: Leaving directory 'openwsman-2.7.2/build'
cp: cannot stat 'build/bindings/ruby/html/': No such file or directory
```
Looks like the `make install` process assumes the Ruby bindings will always be built?

**Comment by kkaempf** [comment]
This should be fixed in 2.8.0
(Building the RPM package without Ruby passes the `make install` step)
