### ISSUE TITLE
 Invalid response to Association query

### ISSUE THREAD

**Issue by georgooty** [Openwsman/openwsman#25]
Hi,

The WS-Management CIM Binding Spec R8.2-1 says, the Assocation query (request with association filter) should be addressed to the "all classes" resource URI. When I send a enumerate request addressed to the CIM_ComputerSystem with the association filter query, I am getting back a EnumerateResponse (with context which fetches the CIM_ComputerSystem with a further Pull request). The spec says the service should return a "wsen:FilterDialectRequestedUnavailable" fault.

If filter dialects is not supported at all with Enumerate, it should return a wsen:FilteringNotSupported fault.

soap request is given below,

https://gist.github.com/georgooty/9eb26dfdcf4385ed7a85

**Comment by kkaempf** [comment]
noresponse
