### ISSUE TITLE
Python bindings give "AttributeError: auth_request_callback" when server returns 401

### ISSUE THREAD

**Issue by dcoshea** [Openwsman/openwsman#35]
With these packages:

```
openwsman-python-2.4.9-127.1.x86_64
libwsman1-2.4.9-127.1.x86_64
```

when I try to connect to a Dell iDRAC from a Python script intentionally using the wrong username and password and use Client.invoke(), this exception traceback appears (_without_ execution being terminated):

```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/pywsman.py", line 1723, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Client, name)
  File "/usr/lib64/python2.6/site-packages/pywsman.py", line 57, in _swig_getattr
    raise AttributeError(name)
AttributeError: auth_request_callback
```

My script then gets a None response from invoke() and can see the 401 response code, etc.

I haven't done anything to set up this auth_request_callback.  I gather that I might be able to call wsmc_transport_set_auth_request_func() to set up a callback, I'm not sure if that would avoid this issue, but in my particular case I don't actually want a callback anyway.  I assume it is a bug that the default behavior results in this exception rather than just doing nothing.

**Comment by kkaempf** [comment]
noresponse
