### ISSUE TITLE
CoreDump due to BinRequestContext->BinRequestHdr->MsgSegment is 0

### ISSUE THREAD

**Issue by raveendrapadala** [Openwsman/openwsman#44]
* We are using: *Openwsman-2.4.10 or 2.4.7, sblim-sfcb-1.4.8, sblim-sfcc-2.2.7*
* For all association commands we are getting a core file whose back trace is given below:
* The actual root cause is due to invalid value for messageSegmentType. 
    *  This issue was observed with upgrade of Opensource codes only. Earlier we were using SFCB.1.3.10 & openwsman 2.3.0 and this issue was never observed.
    * The intInvokeProvider function in providerMgr.c is expecting *MSG_SEG_CHARS 1, MSG_SEG_OBJECTPATH 2, MSG_SEG_INSTANCE 3, MSG_SEG_CONSTCLASS 4, MSG_SEG_ARGS 5, MSG_SEG_QUALIFIER 6* but 
    * The values from core file are as shown below: 

(gdb) print hdr->object[1].type
$1 = 2
(gdb) print hdr->object[2].type
$2 = 1
(gdb) print hdr->object[3].type
$3 = 1
**(gdb) print hdr->object[4].type
$4 = 0** --- This is invalid so going to default scenario where abort() is called.
    *

What could be the reason for "0" to be filled in message segment type? Did anyone faced this issue? kindly share your thoughts on this issue.

Back Trace:
-----------------
Program terminated with signal 6, Aborted.
#0  0x2966c690 in __GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:63
63      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x2966c690 in __GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:63
#1  0x2967029a in __GI_abort () at abort.c:90
#2  0x29e8d2ba in intInvokeProvider (ctx=ctx@entry=0x2a10ec54, sockets=...) at providerMgr.c:1381
#3  0x29e92f8c in invokeProviders (binCtx=0x2a10ec54, err=0x2a10ec50, count=0x2a10ec4c) at providerMgr.c:1542
#4  0x29e4df82 in references (mb=0x423e90, cop=<optimized out>, resultClass=<optimized out>, role=0x0, flags=0, properties=0x0, rc=0x2a10ed40) at cimcClientSfcbLocal.c:1047
#5  0x29e08674 in cim_enum_instances () from /home/Raveendra_Reddy/MY_ACTIVITIES/CORE_ANALYSIS/SFCBUpGrade/debug/usr/lib/openwsman/plugins/libwsman_cim_plugin.so
#6  0x29e106bc in CimResource_Enumerate_EP () from /home/Raveendra_Reddy/MY_ACTIVITIES/CORE_ANALYSIS/SFCBUpGrade/debug/usr/lib/openwsman/plugins/libwsman_cim_plugin.so
#7  0x295e535e in wsenum_enumerate_stub (op=0x41c8a0, appData=0x29e23bac <CimResource_EndPoints+144>, opaqueData=0x0) at /usr/src/debug/openwsman-2.4.10-r4.0/openwsman-2.4.10/src/lib/wsman-soap.c:1012
#8  0x295e09a8 in process_inbound_operation (op=0x41c8a0, msg=0x41c300, opaqueData=0x0) at /usr/src/debug/openwsman-2.4.10-r4.0/openwsman-2.4.10/src/lib/wsman-dispatcher.c:725
#9  0x295e0dce in dispatch_inbound_call (soap=0x41b6a8, msg=0x41c300, opaqueData=0x0) at /usr/src/debug/openwsman-2.4.10-r4.0/openwsman-2.4.10/src/lib/wsman-dispatcher.c:812
#10 0x296174e0 in wsman_server_get_response (arg=0x41b6a8, msg=0x41c300) at /usr/src/debug/openwsman-2.4.10-r4.0/openwsman-2.4.10/src/lib/wsman-server-api.c:150
#11 0x00403b8e in avct_wsman_execute (iReqKey=<optimized out>, fd=5) at /usr/src/debug/wsmanhandler-1.0+git104+9ad61919f1e39322a5722b177df3f76a80d2ee5a-r22.16/source/src/avct_wsman/avct_wsman_proc.c:220
#12 0x00403fda in avct_wsman_execute_proc (pclifd=0x417948) at /usr/src/debug/wsmanhandler-1.0+git104+9ad61919f1e39322a5722b177df3f76a80d2ee5a-r22.16/source/src/avct_wsman/avct_wsman_proc.c:307
#13 0x2957372e in start_thread (arg=0x2a10f4c8) at pthread_create.c:313
#14 0x29721e40 in clone () from /home/Raveendra_Reddy/MY_ACTIVITIES/CORE_ANALYSIS/SFCBUpGrade/debug/lib/libc.so.6
Backtrace stopped: frame did not save the PC

**Comment by kkaempf** [comment]
Closing for now. If issue still happens with Openwsman v2.6.1, please reopen.
