### ISSUE TITLE
Poodle - Suse Linux

### ISSUE THREAD

**Issue by zayan4gh** [Openwsman/openwsman#45]
Hi,
   I am not sure whether this is the right forum to ask this query. If not, please direct me to the same. 
I am  using openwsman bundled with our Suse Linux. The version of openwsman present being as shown below
openwsman-python-2.2.3-0.6.5
openwsman-server-2.2.3-0.6.5
openwsman-client-2.2.3-0.6.5
I want to disable support for SSLv3 for the openwsman server to fix the Poodle vulnerability.(http://www.novell.com/support/kb/doc.php?id=7015773)
I have been unable to find an answer. Please let me know the options for the same.
Thanks
Zayan

**Comment by kkaempf** [comment]
Fixed in v2.4.12
