### ISSUE TITLE
Openwsman should stores invoke() parameters in order

### ISSUE THREAD

**Issue by Tan0** [Openwsman/openwsman#49]
As XML schema use sequence indicators and Openwsman stores invoke() parameters as a hash (set of key/value pairs).
We need a fix within Openwsman to support ordering of add_property() calls.

Like element SetPowerState_INPUT in below schema:
http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_PowerManagementService.xsd

**Comment by kkaempf** [comment]
Sample fix is available at https://github.com/kkaempf/openwsman, branch 'option_properties_as_list'

**Comment by kkaempf** [comment]
Merged in v2.4.13
