### ISSUE TITLE
rdoc2.2 file not found error during make

### ISSUE THREAD

**Issue by akitosh** [Openwsman/openwsman#52]
Hi All, 

I'm trying to compile openwsman 2.4.12 (and 2.4.10) on a CentOS 7 system and am running into the error below. I've also duplicated the error on a RHEL 7 system as well and don't know what to make of it. It seems to be erroring on rdoc and trying to reference version 2.2, but I'm running 4.2.0 of rdoc. I am however running ruby 2.2.0, so not sure it its thinking it should be looking for 2.2 of rdoc because of the version of ruby I have, though both are the latest versions available. Any ideas would be greatly appreciated.

Creating rdoc documentation .../bin/sh: ./rdoc2.2: No such file or directory
make[2]: *** [bindings/ruby/html] Error 127
make[1]: *** [bindings/ruby/CMakeFiles/ruby_gem.dir/all] Error 2
make: *** [all] Error 2

These are the results of the cmake command I ran.

-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Version 2.4.12
-- Package Version "2.4"
-- Plugin API Version "2.2"
-- Package build timestamp 201501122347
-- Building for x86_64
-- Libraries will be installed in /usr/lib64
-- Configuration will be installed in /etc/openwsman
-- building PAM authentication
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
-- Building Ruby bindings
-- Building Python bindings
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5") 
-- Found PythonInterp: /bin/python (found version "2.7.5") 
-- Found PythonLibs...
-- Building Python...
-- Found Perl: /bin/perl (found version "5.16.3") 
-- Building Perl bindings
-- Found Java: /bin/java (found version "1.7.0.71") 
-- Found JNI: /usr/lib/jvm/jre/lib/amd64/libjawt.so  
-- Building Java bindings
-- Found SWIG: /usr/local/bin/swig (found version "3.0.3") 
-- SWIG 3.0.3 found at /usr/local/bin/swig
-- Python executable: /bin/python
-- Python lib dir: /usr/lib64/python2.7/site-packages
-- Ruby executable: /usr/local/bin/ruby
-- Ruby version: 2.2.0
-- Ruby dir: /usr/local/lib/ruby/vendor_ruby/2.2.0
-- Ruby arch dir: /usr/local/lib/ruby/vendor_ruby/2.2.0/x86_64-linux
-- Ruby include path: /usr/local/include/ruby-2.2.0
-- Java compiler: /bin/javac
-- Java runtime: /bin/java
-- Java archiver: /bin/jar
-- Java archive name: openwsman-x86_64-2.4.12.jar
-- Perl executable: /bin/perl
-- Perl core dir: /usr/lib64/perl5/CORE
-- Perl vendor arch dir: /usr/lib64/perl5/vendor_perl
-- Perl vendor lib dir: /usr/share/perl5/vendor_perl
-- Found CURL: /usr/lib64/libcurl.so (found version "7.29.0") 
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.1") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for crypt.h
-- Looking for crypt.h - found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for CUnit/Basic.h
-- Looking for CUnit/Basic.h - not found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for ifaddrs.h
-- Looking for ifaddrs.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - found
-- Looking for net/if_dl.h
-- Looking for net/if_dl.h - not found
-- Looking for net/if.h
-- Looking for net/if.h - found
-- Looking for pam/pam_appl.h
-- Looking for pam/pam_appl.h - not found
-- Looking for pam/pam_misc.h
-- Looking for pam/pam_misc.h - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for security/pam_appl.h
-- Looking for security/pam_appl.h - found
-- Looking for security/pam_misc.h
-- Looking for security/pam_misc.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Looking for sys/select.h
-- Looking for sys/select.h - found
-- Looking for sys/sendfile.h
-- Looking for sys/sendfile.h - found
-- Looking for sys/signal.h
-- Looking for sys/signal.h - found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - found
-- Looking for sys/sockio.h
-- Looking for sys/sockio.h - not found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for vararg.h
-- Looking for vararg.h - not found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for getifaddrs
-- Looking for getifaddrs - found
-- Looking for alloca
-- Looking for alloca - not found
-- Looking for alloca.h
-- Looking for alloca.h - found
-- Looking for bcopy
-- Looking for bcopy - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of in_addr_t
-- Check size of in_addr_t - failed
-- Check type in_addr_t as HAVE_IN_ADDR_T
-- Check type in_port_t as HAVE_IN_PORT_T
-- Check type sa_family_t as HAVE_SA_FAMILY_T
-- Check type int as HAVE_INT
-- Check type long as HAVE_LONG
-- Check type long long as HAVE_LONG_LONG
-- Check type short as HAVE_SHORT
-- Performing Test HAVE_SA_LEN
-- Performing Test HAVE_SA_LEN - Failed
-- Performing Test HAVE_IPV6
-- Performing Test HAVE_IPV6 - Success
-- SSL_LIB is at >libssl.so.1.0.1e<
-- Package file openwsman-2.4.12
-- Configuring done
-- Generating done
-- Build files have been written to: /root/openwsman-2.4.12/build

And these are the results of the make command I ran afterwards.

Scanning dependencies of target wsman_curl_client_transport
[  1%] Building C object src/lib/CMakeFiles/wsman_curl_client_transport.dir/wsman-client-transport.o
[  2%] Building C object src/lib/CMakeFiles/wsman_curl_client_transport.dir/wsman-curl-client-transport.o
Linking C shared library libwsman_curl_client_transport.so
[  2%] Built target wsman_curl_client_transport
Scanning dependencies of target wsman_client
[  2%] Building C object src/lib/CMakeFiles/wsman_client.dir/wsman-client.o
Linking C shared library libwsman_client.so
[  2%] Built target wsman_client
Scanning dependencies of target wsman
[  2%] Building C object src/lib/CMakeFiles/wsman.dir/u/buf.o
[  3%] Building C object src/lib/CMakeFiles/wsman.dir/u/log.o
[  4%] Building C object src/lib/CMakeFiles/wsman.dir/u/memory.o
[  5%] Building C object src/lib/CMakeFiles/wsman.dir/u/misc.o
[  6%] Building C object src/lib/CMakeFiles/wsman.dir/u/uri.o
[  7%] Building C object src/lib/CMakeFiles/wsman.dir/u/uuid.o
[  8%] Building C object src/lib/CMakeFiles/wsman.dir/u/lock.o
[  9%] Building C object src/lib/CMakeFiles/wsman.dir/u/md5.o
[ 10%] Building C object src/lib/CMakeFiles/wsman.dir/u/strings.o
[ 10%] Building C object src/lib/CMakeFiles/wsman.dir/u/list.o
[ 11%] Building C object src/lib/CMakeFiles/wsman.dir/u/hash.o
[ 12%] Building C object src/lib/CMakeFiles/wsman.dir/u/base64.o
[ 13%] Building C object src/lib/CMakeFiles/wsman.dir/u/iniparser.o
[ 14%] Building C object src/lib/CMakeFiles/wsman.dir/u/debug.o
[ 15%] Building C object src/lib/CMakeFiles/wsman.dir/u/uerr.o
[ 16%] Building C object src/lib/CMakeFiles/wsman.dir/u/uoption.o
[ 17%] Building C object src/lib/CMakeFiles/wsman.dir/u/gettimeofday.o
[ 18%] Building C object src/lib/CMakeFiles/wsman.dir/u/syslog.o
[ 18%] Building C object src/lib/CMakeFiles/wsman.dir/u/pthreadx_win32.o
[ 19%] Building C object src/lib/CMakeFiles/wsman.dir/u/os.o
[ 20%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-libxml2-binding.o
[ 21%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-xml.o
[ 22%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-epr.o
[ 23%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-filter.o
[ 24%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-dispatcher.o
[ 25%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-soap.o
[ 26%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-faults.o
[ 27%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-xml-serialize.o
[ 27%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-soap-envelope.o
[ 28%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-debug.o
[ 29%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-soap-message.o
[ 30%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-subscription-repository.o
[ 31%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-event-pool.o
[ 32%] Building C object src/lib/CMakeFiles/wsman.dir/wsman-cimindication-processor.o
Linking C shared library libwsman.so
[ 32%] Built target wsman
[ 33%] Generating openwsman_wrap.c
Creating wrapper code for Python ...Done.
Scanning dependencies of target pywsman
[ 34%] Building C object bindings/python/CMakeFiles/pywsman.dir/openwsman_wrap.o
[ 34%] Building C object bindings/python/CMakeFiles/pywsman.dir/__/openwsman.o
Linking C shared library _pywsman.so
[ 34%] Built target pywsman
[ 35%] Generating openwsman_wrap.c
Creating wrapper code for Ruby...Done.
Scanning dependencies of target rbwsman
[ 36%] Building C object bindings/ruby/CMakeFiles/rbwsman.dir/openwsman_wrap.o
[ 37%] Building C object bindings/ruby/CMakeFiles/rbwsman.dir/__/openwsman.o
Linking C shared library _openwsman.so
[ 37%] Built target rbwsman
Scanning dependencies of target ruby_gem
[ 38%] Generating ext
[ 39%] Generating html
Creating rdoc documentation .../bin/sh: ./rdoc2.2: No such file or directory
make[2]: *** [bindings/ruby/html] Error 127
make[1]: *** [bindings/ruby/CMakeFiles/ruby_gem.dir/all] Error 2
make: *** [all] Error 2

**Comment by kkaempf** [comment]
This is no plain CentOS / RHEL system you're running on, right ?

Apparently you have Ruby 2.2 installed which was just released ~2 weeks ago.

**Comment by kkaempf** [comment]
fixed in 886fcfeec942c0411520d7eb700a389e3d87c1c9

**Comment by akitosh** [comment]
Thanks a lot. Tested and it works on ruby 2.2.

**Comment by kkaempf** [comment]
Great, thanks for the feedback !
