### ISSUE TITLE
Memory leak in wsman-libxml2-binding.c

### ISSUE THREAD

**Issue by x3nhydr4lutr1sx** [Openwsman/openwsman#57]
Here's my personal patch for 2.4.10. 

diff -r 310f9ade3294 -r 1afab5e6a399 src/lib/wsman-libxml2-binding.c
--- src/lib/wsman-libxml2-binding.c	Sun Feb 22 11:56:20 2015 -0800
+++ src/lib/wsman-libxml2-binding.c	Mon Feb 23 20:27:16 2015 -0800
@@ -906,6 +906,7 @@
 		xmlXPathFreeContext(ctxt);
 		xmlXPathFreeObject(obj);
 	} else {
+.		xmlXPathFreeContext(ctxt);
 		return 0;
 	}
 
@@ -949,6 +950,7 @@
 		xmlXPathFreeContext(ctxt);
 		xmlXPathFreeObject(obj);
 	} else {
+.		xmlXPathFreeContext(ctxt);
 		return NULL;
 	}

**Comment by kkaempf** [comment]
Good catch, thanks !

Fixed slightly differently. ;-)
