### ISSUE TITLE
CQL dialect name not using "DMTF:CQL" format

### ISSUE THREAD

**Issue by micskeiz** [Openwsman/openwsman#60]
I tried to execute the following CQL query:

    wsman -h localhost -u user -p pass  enumerate 'http://schemas.dmtf.org/wbem/wscim/1/*'  --dialect="http://schemas.dmtf.org/wbem/cql/1/dsp0202.pdf" --filter="SELECT Name, VendorName FROM CIM_PCIDevice WHERE ClassCode = 12"

If the local CIMOM is sblim-sfcb, then it works perfectly. 

However, if the CIMOM is OpenPegasus, then CIM_ERR_QUERY_LANGUAGE_NOT_SUPPORTED is returned.

(I tried on a Fedora 21 Server Minimal x86, tog-pegasus.i686 2:2.13.0-17.fc21, openwsman-server.i686 2.4.6-3.fc21).

The problem is, that for the ExecQuery CIM-XML call openwsman sets the query language to "CQL", while OpenPegasus expects "DMTF:CQL".

If I change it in sfcc-interface.c:1191, then the query is executed successfully. 

As far as I see in version 1.0.0 of DSP202 'CIM Query Language Specification', Section 6.1  Identifying the CIM Query Language:

> Following this convention, the string "DMTF:CQL" identifies the CIM Query Language.

Moreover, sblim-sfcb also accepts the DMTF:CQL format. In version 1.4.9, querystatement.c, line 277:

    else if (strcasecmp(lang, "cql") == 0 || strcasecmp(lang, "cim:cql") == 0 || strcasecmp(lang, "dmtf:cql") == 0) {
      ctl.statement->lang = QL_CQL;

Of course changing this could break compatibility with other apps. Maybe it could be a configuration setting?

**Comment by kkaempf** [comment]
Thanks for the report !

Yes, this needs to be configurable since e.g. sblim-sfcb 1.3.11 (used on SUSE Linux Enterprise Serevr 11) requires `CQL`

Added new config option `cim_client_cql`, defaults to `CQL`

**Comment by kkaempf** [comment]
Fixed
