### ISSUE TITLE
Support for WS-Man Spec 1.2.0 binary attachments (Section 13.5)

### ISSUE THREAD

**Issue by raveendrapadala** [Openwsman/openwsman#61]
Hi Klaus,

What is the plan of supporting WSMan specification 1.2.0 and supporting binary attachment transfer as defined in Section 13.5

Thank you.

**Comment by kkaempf** [comment]
Let me check section 13.5 on how complex this might be.

**Comment by kkaempf** [comment]
Hmm, this might not be complex code-wise but needs full understanding of the SOAP MTOM standard.

@raveendrapadala: Any proposal how to test it ?

**Comment by raveendrapadala** [comment]
Klaus, 
Let me look in to the SOAP MTOM Standard and get back to you with detailed test plan. Mostly we are looking for custom actions (methods).

**Comment by kkaempf** [comment]
noresponse
