### ISSUE TITLE
Support for credential delegation using CredSSP for multi-hop scenarios

### ISSUE THREAD

**Issue by wcewarrior** [Openwsman/openwsman#62]
Hi Klaus,

Does openwsman support CredSSP as an authentication method? If not, is there a way to invoke a remote winrm method that involves a multi-hop (let's say a remote method that lists files on another file server).

If this is not supported today, are there any plans to implement this in near future? FreeRDP project seems to have implemented the SSPI authentication (NTLM, kerberos, negotiate, CredSSP) in a cross-platform way which could be re-used (see https://github.com/FreeRDP/FreeRDP/tree/master/winpr/libwinpr).

Thanks,
Shreyas

**Comment by kkaempf** [comment]
Sorry, no, there are no plans to add this.

If you get this implemented, I'd be happy to accept your pull request.
