### ISSUE TITLE
Expose the method to set underlying transport timeout from the C++ binding

### ISSUE THREAD

**Issue by shreyas-agnihotri** [Openwsman/openwsman#63]
Hi Klaus,

For C binding, we can set the timeout using wsman_transport_set_timeout method in wsman-client-transport.c, but it is not exposed from the C++ binding (OpenWsmanClient class). Can you please add the corresponding method in OpenWsmanClient class? This will be useful since libcurl requires timeout to be set explicitly or the transport will not timeout on linux in case of error (causing the application to hang).

Thanks,
Shreyas

**Comment by prabhakarpujeri** [comment]
https://github.com/Openwsman/openwsman/commit/74186fdcd52f438181e78482cb6da5ec3c48d82d

this patch added transport timeout for c++ binding

**Comment by shreyas-agnihotri** [comment]
Appreciate it. Thanks!

**Comment by kkaempf** [comment]
Committed to master
