### ISSUE TITLE
V2.4.14 Perl $options->add_property() - core for the second property call

### ISSUE THREAD

**Issue by ftsckae** [Openwsman/openwsman#64]
Hello,

I'm testing Perl Openwsman 2.4.14 and "Invoke"s.

It is working well for methods with multiple selector keys and none or one "argument".

BUT I'm getting a signal core hint for multiple "arguments".
                This happens inside the second add_property call.

Here an Perl script function extract for "Invokes" of our (future) Nagios tool:

  sub cimWSMANInvoke {
     my $iClass = shift;
     my $iMethod = shift;
     return if (!$iClass or !$iMethod);

     my $class = ...; # … namespace checks of $iClass …
     
     # Set up client options.
     my $options = new openwsman::ClientOptions::();
     if (!$options) {
           # …
           return;
     }
     # Dump the XML request to stdout.
     $options->set_dump_request() if ($main::verbose>=60);

     # $options->add_selector("__cimnamespace", … );

     # ..... Selectors
     my %selectors = …;
     foreach my $key (keys %selectors) {
         my $value = undef;
         $value = $selectors{$key};
         $options->add_selector($key, $value) if ($key and defined $value);
     }

     # ..... Parameters
     my %properties = …;
     foreach my $key (keys %properties) {
         my $value = undef;
         $value = $properties{$key};
         $options->add_property($key, $value) if ($key and defined $value);
     }

     # ..... Invoke
     my $result = undef; # Used to store obtained data.
     $result = $clientSession->invoke($options, $class, $iMethod);
     if ($main::verbose >= 60 and $result) {
         $result->dump_file(*STDOUT);
     }
     unless($result && $result->is_fault eq 0) {
         # …
         return;
     }    
                # …
  }

**Comment by kkaempf** [comment]
Since you're using 2.4.14, I assume you compile from source.

Can you please checkout the `key_value_t` branch from `https://github.com/kkaempf/openwsman.git` ?This has significant changes in the selector and property handling.

**Comment by kkaempf** [comment]
If this is not possible, please inspect the `core` file with gdb and report where the crash happens.

**Comment by ftsckae** [comment]
… there was a rpm in http://download.opensuse.org/repositories/Openwsman/RedHat_RHEL-6/x86_64/

**Comment by ftsckae** [comment]
With gdb /usr/lib64/libwsman.so.1 core.* and "where":

Loaded symbols for /lib64/libselinux.so.1
Core was generated by `/usr/bin/perl ./fujitsu_server_wsman.pl --invoke -CSVS_PGYUpdateJob --method Re'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000359bd2683a in __strcmp_sse42 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install libwsman1-2.4.14-147.1.x86_64
(gdb) where
#0  0x000000359bd2683a in __strcmp_sse42 () from /lib64/libc.so.6
#1  0x00000038a9a102a4 in ow_list_find () from /usr/lib64/libwsman.so.1
#2  0x00000038aa204944 in ?? () from /usr/lib64/libwsman_client.so.2
#3  0x00007ff9f445a812 in _wrap_ClientOptions_add_property__SWIG_0 ()
   from /usr/lib64/perl5/vendor_perl/openwsman.so
#4  0x00007ff9f445b022 in _wrap_ClientOptions_add_property ()
   from /usr/lib64/perl5/vendor_perl/openwsman.so
#5  0x000000359c4a66d5 in Perl_pp_entersub ()
   from /usr/lib64/perl5/CORE/libperl.so
#6  0x000000359c4a49c6 in Perl_runops_standard ()
   from /usr/lib64/perl5/CORE/libperl.so
#7  0x000000359c44d0d8 in perl_run () from /usr/lib64/perl5/CORE/libperl.so
#8  0x0000000000400cac in ?? ()
#9  0x0000000000000000 in ?? ()

--ckae

**Comment by kkaempf** [comment]
Ah, that one:
https://github.com/Openwsman/openwsman/commit/3f22c34531829d3fb01a244160485757ba94b168
