### ISSUE TITLE
wsmancli-2.3.2-54.6 can't parse keys (selectors) properly for Dell PowerEdge with LifeCycle Controller 2

### ISSUE THREAD

**Issue by sdtechz** [Openwsman/openwsman#69]
As you can see below, it seems that wsmancli-2.3.2-54.6 parsed multiple keys (selectors) as a single key (selector). Whereas, wsmancli-2.3.0-41.6 parsed multiple keys correctly. 

------------------------------------------------------------------------------
rpm -qa | grep wsman
wsmancli-2.3.2-54.6
libwsman1-2.4.15-148.1

Example command:
wsman invoke -a GetRAIDLevels http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_RAIDService?SystemCreationClassName=DCIM_ComputerSystem,CreationClassName=DCIM_RAIDService,SystemName=DCIM:ComputerSystem,Name=DCIM:RAIDService -h 192.168.1.100 -V -v -c dummy.cert -P 443 -u root -p calvin -J GetRAIDLevels.xml -j utf-8 -y basic -R -d 6

Example output:
May 29 10:11:48  key=SystemCreationClassName value=DCIM_ComputerSystem,CreationClassName=DCIM_RAIDService,SystemName=DCIM:ComputerSystem,Name=DCIM:RAIDService

    <wsman:SelectorSet>
      <b><wsman:Selector Name="SystemCreationClassName">DCIM_ComputerSystem,CreationClassName=DCIM_RAIDService,SystemName=DCIM:ComputerSystem,Name=DCIM:RAIDService</wsman:Selector>
    </wsman:SelectorSet></b>

rpm -qa | grep wsman
libwsman1-2.3.7-89.2
wsmancli-2.3.0-41.6

Same command as above, but the key (selector) is properly parsed:

Jun  2 09:52:23  key = Name value=DCIM:RAIDService
Jun  2 09:52:23  key = SystemName value=DCIM:ComputerSystem
Jun  2 09:52:23  key = CreationClassName value=DCIM_RAIDService
Jun  2 09:52:23  key = SystemCreationClassName value=DCIM_ComputerSystem

<wsman:SelectorSet>
      <wsman:Selector Name="Name">DCIM:RAIDService</wsman:Selector>
      <wsman:Selector Name="SystemName">DCIM:ComputerSystem</wsman:Selector>
      <wsman:Selector Name="CreationClassName">DCIM_RAIDService</wsman:Selector>
      <wsman:Selector Name="SystemCreationClassName">DCIM_ComputerSystem</wsman:Selector>
    </wsman:SelectorSet>

**Comment by kkaempf** [comment]
That's a regression introduced in libwsman1-2.4.11, I just updated the release notes on github.

Your query parameter for the resource URI is wrong, you must use ampersand `&` to separate selectors.

**wrong** `SystemCreationClassName=DCIM_ComputerSystem,CreationClassName=DCIM_RAIDService,SystemName=DCIM:ComputerSystem,Name=DCIM:RAIDService`

**right** `SystemCreationClassName=DCIM_ComputerSystem&CreationClassName=DCIM_RAIDService&SystemName=DCIM:ComputerSystem&Name=DCIM:RAIDService`

libwsman1-2.5.1 prints a warning if you use `,`
