### ISSUE TITLE
'yum install libwsman1 openwsman-python' on CentOS 6 gives "Transaction Check Error"

### ISSUE THREAD

**Issue by dcoshea** [Openwsman/openwsman#71]
I have a script to install the Openwsman packages (and other packages) my script requires on CentOS 6, and it did this by fetching http://download.opensuse.org/repositories/Openwsman/CentOS_CentOS-6/Openwsman.repo and then using using `yum install libwsman1 openwsman-python [... other packages ...]` to do this.  Recently it started failing with:

```
Dependencies Resolved

================================================================================
 Package              Arch       Version            Repository             Size
================================================================================
Installing:
[...]
 libwsman1            x86_64     2.2.3-8.el6        base                  112 k
 openwsman-python     x86_64     2.6.0-156.1        Openwsman             123 k
[...]
Installing for dependencies:
 libwsman3            x86_64     2.6.0-156.1        Openwsman             139 k

[...]
Downloading Packages:
[...]
Transaction Check Error:
  file /usr/lib64/libwsman.so.1.0.0 conflicts between attempted installs of libwsman3-2.6.0-156.1.x86_64 and libwsman1-2.2.3-8.el6.x86_64
  file /usr/lib64/libwsman_curl_client_transport.so.1.0.0 conflicts between attempted installs of libwsman3-2.6.0-156.1.x86_64 and libwsman1-2.2.3-8.el6.x86_64
```

I don't really want both libwsman1 and libwsman3 installed, and have updated my script.  However, my understanding of RPM packaging is that the incompatibility between the two should not have been picked up based on them containing the same files.  If they aren't intended to be able to be installed side-by-side, then shouldn't libwsman3 have "Obsoletes:" and/or "Conflicts:" in it?  Or if they are intended to be installed side-by-side, obviously some filenames need to change.

Note that CentOS's base repository provides libwsman1, which is why both it and libwsman3 were found.

**Comment by kkaempf** [comment]
Thanks for the report, added 'Obsoletes: libwsman1' now to libwsman3
