### ISSUE TITLE
Version changes in CMake not carried over to other files

### ISSUE THREAD

**Issue by L2G** [Openwsman/openwsman#72]
The version number change made in [VERSION.cmake](https://github.com/Openwsman/openwsman/blob/879ec95928a43a4077aa77204606063bd95c36db/VERSION.cmake#L48-L50) has not been carried over to other files such as [configure.ac](https://github.com/Openwsman/openwsman/blob/879ec95928a43a4077aa77204606063bd95c36db/configure.ac#L13-L15).

A naive user who attempts to build this by going straight to the GNU build tools and the autoconfiscate.sh script could end up installing openwsman with incorrect pkg-config metadata, making it impractical to build tools (such as wsmancli) dependent on it.

If users are supposed to build everything from scratch with CMake every time, then it may be better simply to remove all CMake products from the GitHub repo.

**Comment by kkaempf** [comment]
autotools are deprecated for building Openwsman. I added a warning to autoconfiscate.sh now.
