### ISSUE TITLE
options/selectors_from_uri handles only queries and not complete uris

### ISSUE THREAD

**Issue by kolbma** [Openwsman/openwsman#77]
Hi,

there is a bug at https://github.com/Openwsman/openwsman/blob/master/src/lib/wsman-client.c#L561

2nd argument needs to be only a query. Here is provided the complete uri.

That's the cause of https://bugzilla.opensuse.org/show_bug.cgi?id=947422

**Comment by kkaempf** [comment]
See my comment in your commit. Next create a pull request please !

**Comment by kkaempf** [comment]
Request merged.
