### ISSUE TITLE
Update the Prebuilt RPMs?

### ISSUE THREAD

**Issue by ruckc** [Openwsman/openwsman#79]
Any chance the prebuild RPMs could be updated to 2.6.1?  Would really like to get wsman's WinRM cli support working from Linux.

**Comment by kkaempf** [comment]
https://build.opensuse.org/package/show/Openwsman/openwsman has 2.6.1
Maybe there's an outdated link somewhere on the Web, where did you go for the RPMs ?

**Comment by ruckc** [comment]
Your WIKI link points to the old versions... https://github.com/Openwsman/openwsman/wiki/Pre-built-RPM-packages
