### ISSUE TITLE
Fix RPM build errors for 2.6.1

### ISSUE THREAD

**Issue by ruckc** [Openwsman/openwsman#80]
RHEL6, RHEL5, and CentOS 6 are showing this build error, not sure why this isn't breaking on other builds.

    ./openwsman-2.6.1/include/wsman-epr.h:64: error: redefinition of typedef 'epr_t'
    ./openwsman-2.6.1/include/wsman-key-value.h:44: note: previous declaration of 'epr_t' was here

**Comment by kkaempf** [comment]
Fixed by 04b84ccb

**Comment by kkaempf** [comment]
Oh, btw, https://build.opensuse.org/package/show/Openwsman/openwsman is already fixed.
