### ISSUE TITLE
Remove autotools build system?

### ISSUE THREAD

**Issue by UniqMartin** [Openwsman/openwsman#88]
As can be read [in the wiki](https://github.com/Openwsman/openwsman/wiki/Build-requirements) the autotools build system is no longer maintained and judging from the commit history, hasn't been touched in years. [`autoconfiscate.sh`](https://github.com/Openwsman/openwsman/blob/4e54d3ee9d5830154a94e6cdc883c43bcc860e73/autoconfiscate.sh#L3-L5) prints a warning to that end, but that's easily overlooked, particularly when the build happens in an automated setting. The problem with continuing to provide those files is that things continue to build, but the result is incomplete (newer headers are not copied to their destination) or possibly even broken (not sure about that).

Suggestions (in order of preference):

- Remove all traces of the autotools build system.
- Turn the `autoconfiscate.sh` warning into an error and require the user to pass an additional argument to continue past that warning.

If either of these are acceptable, I'm happy to prepare a PR.

*Background:* This came up while reviewing the `openwsman` package as provided by the Homebrew package manager for OS X. Because it still uses the autotools build system, the install is incomplete and the `wsmancli` package, that happens to depends on `openwsman`, fails to build. See Homebrew/legacy-homebrew#44047 for the full context.

**Comment by prlw1** [comment]
The cmake build doesn't work for me, so if you remove autoconf too, then how can I build? bug #87

**Comment by kkaempf** [comment]
@UniqMartin I'd prefer the second option (`autoconfiscate.sh` erroring out), hopefully someone's fixing the autotool problems then.

@prlw1 what's the problem with cmake ?

**Comment by UniqMartin** [comment]
> I'd prefer the second option (`autoconfiscate.sh` erroring out), […]

Done in #90.

**Comment by apjanke** [comment]
I found a couple problems with OS X support in the CMake stuff, including @prlw1's `/bin/uname` vs `/usr/bin/uname` problem. They're fixable, and I'm going to take a stab at it. See #92.

**Comment by UniqMartin** [comment]
@apjanke Note that there's also #89 with a minor fix and some discussion, in case you missed it.

**Comment by apjanke** [comment]
I did in fact miss that; thanks. Incorporated its outstanding issues into #92.
