### ISSUE TITLE
Inconsistent code style in CMake files

### ISSUE THREAD

**Issue by apjanke** [Openwsman/openwsman#91]
I've been reading through the CMake files while getting Openwsman to build on OS X. The code style is pretty inconsistent, which makes it harder to read. Would you entertain a PR to reformat the CMake files to a consistent style?

Aspects:
- uppercase vs lowercase function names (currently mixed, with uppercase seeming to predominate; I find lowercase more readable though)
- indent size (looks like 2 spaces is most common here
- indenting everything inside `IF` or `WHILE` blocks
- space between function name and opening parenthesis for its arguments?
- space inside parentheses enclosing function arguments?
- hard-wrapping very long lines?

If it's something you'd consider, I'll make a PR doing the reformatting.

**Comment by kkaempf** [comment]
Yes, this is welcome. Just make sure that it only changes style, not semantics. ;-)

**Comment by kkaempf** [comment]
No PR received.
