### ISSUE TITLE
OS X support in new CMake build system

### ISSUE THREAD

**Issue by apjanke** [Openwsman/openwsman#92]
The current state of the new CMake build system doesn't work on OS X. There are a few platform-specific factors causing it.

I'm an OS X user and Homebrew maintainer and am working on getting it to build there, following up on https://github.com/Homebrew/legacy-homebrew/issues/44047#issuecomment-215642197. If I can get it running, I'll supply a PR for this, but wanted to get the bug report in place first, and get a little feedback.

See also #89.

###  Issues  ###

* `/bin/uname` vs `/usr/bin/uname` – on OS X, it's `/usr/bin/uname`, but the CMakeLists is hardcoded to use `/bin/uname` (may be same as #87)
* No `lib64` – OS X does not have separate `lib` and `lib64` directories (at least on 10.9+), so 64-bit libraries should be installed in `lib` there; currently they're going to `lib64`.
* Warning on unset Mac-specific policy `CMP0042`
* Unresolved symbols linked dynamically at run time
* Similar deferred linkage to OpenSSL when eventing is enabled (see #89)
* Non-portable introspection of `libssl.so` (see #89)

####   Linking unresolved symbols at run time  ####

Openwsman provides multiple DLLs, and the way they're structured and linked currently, many depend on each other and have symbols that are left unresolved at compile + link time. Looks like these are intended to defer the resolution to program run time, and a program using them must link against multiple Openwsman libs to get all the symbols resolved. CMake supports this, but it's not the default behavior on OS X. (Maybe it is on Linux.)

Defining a library as `MODULE` instead of `SHARED` in the `add_library` arguments supports this delayed resolution on OS X. But CMake doesn't permit cyclical dependencies between dynamic libraries. And there's a dependency cycle in the openwsman libraries. This may be a bit tricky to fix.

I was able to get it to build by manually adding the deferred-symbol-resolution linker flags instead of relying on CMake's MODULE support using the following target properties.

```
set_target_properties( ${WSMAN_CLIENTPP_PKG} PROPERTIES LINK_FLAGS "-undefined dynamic_lookup")
```

But that's kind of a hack, and may not work with all compilers on OS X.

Are the cyclical dependencies in the dylibs intentional?

##   Work in progress   ##

Working on this at https://github.com/apjanke/openwsman/tree/osx-cmake-support.

I've got the `uname`, `lib64`, and policy issues handled. Waiting to tackle the deferred linkage until I hear back about whether the cyclical dependencies are intentional and necessary.

**Comment by prlw1** [comment]
Bug #87 has the hard coded /bin/uname issue, but also the C_ALLOCA failure: as explained over there, cmake generates an incorrect wsman_config.h:

/* Define to 1 if using `alloca.c'. */
#if
#define C_ALLOCA 1
#endif

Note the lack of anything after the "#if" - more detail in bug #87. (Suggests that cmake isn't ready for prime time and that removing autoconf support is premature.)

**Comment by kkaempf** [comment]
I'd be very thankful if you provider separate PRs for the issues listed above.

**Comment by kkaempf** [comment]
The `C_ALLOCA` problem apparently appears if the `alloca` exists.

**Comment by kkaempf** [comment]
Where is the cycle in dynamic libraries ? This should be fixable by moving functions.

**Comment by kkaempf** [comment]
I cherry-picked a504592 and 6039945 from https://github.com/apjanke/openwsman/tree/osx-cmake-support to upstream/master.

**Comment by UniqMartin** [comment]
@kkaempf Thanks for picking these! I guess as Homebrew maintainers (@apjanke and me), but not active users of this software, there's only so much we can do …
