### ISSUE TITLE
wsmc_set_locale and wsmc_add_property_epr are undefined symbol in _pywsman.so file

### ISSUE THREAD

**Issue by idonotknow** [Openwsman/openwsman#93]
I got an error when import pywsman on ubuntu14.04. I have compiled pywsman in directory openwsman/bindings/python/pywsman. It did output _pywsman.so file,but as you see,when I use that ,error occurs.

**Comment by kkaempf** [comment]
Did you use autotools (automake/autoconf) or CMake ?

**Comment by idonotknow** [comment]
@kkaempf I used CMake.

**Comment by kkaempf** [comment]
Where did you get the openwsman package from ?
Did you build yourself ? Do you have Python3 installed ? Then https://cmake.org/Bug/view.php?id=13794 is your issue. Remove Python3 (devel package) and try again.

**Comment by kkaempf** [comment]
No further feedback. Closing.
