### ISSUE TITLE
Cant invoke a method with array type parameters.

### ISSUE THREAD

**Issue by korizza** [Openwsman/openwsman#95]
Hi guys! Could you give me a short example how to invoke a CIM method with array type parameters using java implementation of openwsman.

**Comment by korizza** [comment]
I was trying to add array type parameters using 'add_property' function, but it denies to add more than one items with the same key into '_INPUT' tag. For example, we have a CIM method:

`	[Implemented]
	sint32 foo(
		[IN, Description ("Array of strings.")]
                string strArr[],
		[IN, Description ("Array of reals.")]
                real32 realArr[],
	);`
suppose, I need to pass strArr['val0', 'val1', 'val3'] and realArr[50.0, 50.0]. In this case openwsman creates the following xml:
`  <s:Body>
    <n1:foo_INPUT>
      <n1:strArr>val0</n1:strArr>
      <n1:realArr>50.0</n1:realArr>
    </n1:foo_INPUT>
  </s:Body>`

Then, I make changes in 'src/lib/wsman-client.c'  file:

`static void
_wsmc_add_key_value(list_t **list_ptr,
		const char *key,
		const char *string,
		const epr_t *epr)
{
  key_value_t *kv;
  list_t *list = *list_ptr;
  lnode_t *lnode;
  if ((string != NULL) && (epr != NULL)) {
    error("Ambiguous call to add_key_value");
    return;
  }
  if (key == NULL) {
    error("Can't add_key_value with NULL key");
    return;
  }
  if (list == NULL) {
    list = list_create(LISTCOUNT_T_MAX);
    *list_ptr = list;
  }
/*
  if (list_find(list, key, _list_key_compare)) {
    error("duplicate key not added to list");
    return;
  }
*/
  kv = key_value_create(key, string, epr, NULL);
  if (!kv) {
    error("No memory for key/value pair");
    return;
  }
  lnode = lnode_create(kv);
  if (!lnode) {
    error("No memory for key/value node");
    return;
  }
  list_append(list, lnode);
}`

I've commented a block of code that denies to add properties with the same key. After that the xml was:
`  <s:Body>
    <n1:foo_INPUT>
      <n1:strArr>val0</n1:strArr>
      <n1:strArr>val1</n1:strArr>
      <n1:strArr>val3</n1:strArr>
      <n1:realArr>50.0</n1:realArr>
      <n1:realArr>50.0</n1:realArr>
    </n1:foo_INPUT>
  </s:Body>`

So, the method has been called and processed succesfully after my changes. Please, take a look.
I'm using java binding of openwsman ver. 2.6.0

Thank you.

**Comment by kkaempf** [comment]
Uhm, right, array types need to be handled separately.

**Comment by korizza** [comment]
Ok, I'll add some overloaded method for it in my fork and send you a merge request. what you think?

**Comment by korizza** [comment]
I added 'add_property_array_item' in java binding. Usage:

```
        public synchronized XmlNode invoke(String cimClassName,
                                      String cimNamespace,
                                      String cimMethodName,
                                      Pair<String, Object> keyFieldValue,
                                      Map<String, Object> inParams) throws CimException {

...

        // add method's input parameters
        if (inParams != null) {
            inParams.forEach((key, value) -> {
                if (value instanceof List) {
                    for (Object item : (List)value) {
                        clientOptions.**add_property_array_item**(key, item.toString());
                    }
                } else {
                    clientOptions.add_property(key, value.toString());
                }
            });
        }

```

this code works for me. Please take a look.
Than you.
