### ISSUE TITLE
Openwsman 2.6.3 Build error on Ubuntu 14.04

### ISSUE THREAD

**Issue by yw529** [Openwsman/openwsman#97]
Wonder if anyone has built latest openwsman 2.6.3 successfully on Ubuntu 14.04? Managed to solve most of the build dependency problem to reach 93%, can't tell if some of the errors in CMakeFiles/CMakeError.log are expected? Any help will be highly appreciated.

1. cmake produced several NOT FOUND errors (only copied error messages below), wonder if they are expected? 
wsman/openwsman-2.6.3/build# cmake ..
-- The C compiler identification is GNU 4.6.4
-- The CXX compiler identification is GNU 4.6.4
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for net/if_dl.h - not found
-- Looking for pam/pam_appl.h - not found
-- Looking for pam/pam_misc.h - not found
-- Looking for sys/sockio.h - not found
-- Looking for vararg.h - not found
-- Looking for alloca - not found
-- Check size of in_addr_t - failed
-- Performing Test HAVE_SA_LEN - Failed
-- Performing Test HAVE_IPV6
-- Performing Test HAVE_IPV6 - Success
-- SSL_LIB is at ><
-- Package file openwsman-2.6.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ywang1/Desktop/wsman/openwsman-2.6.3/build
 
2. make failed at 93%:
[ 91%] Building C object src/server/CMakeFiles/openwsmand.dir/gss.o
[ 92%] Building C object src/server/CMakeFiles/openwsmand.dir/wsmand.o
[ 93%] Linking C executable openwsmand
../lib/libwsman.so.1.0.0: error: undefined reference to 'floor'
collect2: ld returned 1 exit status
make[2]: *** [src/server/openwsmand] Error 1
make[1]: *** [src/server/CMakeFiles/openwsmand.dir/all] Error 2
make: *** [all] Error 2

3. Some errors from CMakeError.log:
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_02642.dir/CheckFunctionExists.c.o  -o cmTC_02642 -rdynamic -lpthreads
/usr/bin/ld: error: cannot find -lpthreads
CMakeFiles/cmTC_02642.dir/CheckFunctionExists.c.o:CheckFunctionExists.c:function main: error: undefined reference to 'pthread_create'
collect2: ld returned 1 exit status
make[1]: Leaving directory `/home/ywang1/Desktop/wsman/openwsman-2.6.3/build/CMakeFiles/CMakeTmp'
make[1]: *** [cmTC_02642] Error 1
make: *** [cmTC_02642/fast] Error 2

/usr/bin/cc     -o CMakeFiles/cmTC_3d12f.dir/CheckIncludeFile.c.o   -c /home/ywang1/Desktop/wsman/openwsman-2.6.3/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/ywang1/Desktop/wsman/openwsman-2.6.3/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:23: fatal error: net/if_dl.h: No such file or directory
compilation terminated.
make[1]: Leaving directory `/home/ywang1/Desktop/wsman/openwsman-2.6.3/build/CMakeFiles/CMakeTmp'
make[1]: *** [CMakeFiles/cmTC_3d12f.dir/CheckIncludeFile.c.o] Error 1
make: *** [cmTC_3d12f/fast] Error 2

/usr/bin/cc     -o CMakeFiles/cmTC_5c891.dir/CheckIncludeFile.c.o   -c /home/ywang1/Desktop/wsman/openwsman-2.6.3/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/ywang1/Desktop/wsman/openwsman-2.6.3/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:26: fatal error: pam/pam_appl.h: No such file or directory
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_5c891.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory `/home/ywang1/Desktop/wsman/openwsman-2.6.3/build/CMakeFiles/CMakeTmp'
make: *** [cmTC_5c891/fast] Error 2

**Comment by kkaempf** [comment]
Uhm, Ubuntu 14.04 is pretty old already and I have no Debian/Ubuntu experience.

Someone from the community used to maintain packages at https://build.opensuse.org/package/show/Openwsman/openwsman-deb but this project seems to be abandoned.

Please reach out to the mailing list at openwsman-devel@lists.sourceforge.net where other openwsman developers hopefully can help you.

**Comment by yw529** [comment]
Thank you. I will move the question to the mailing list.
